<a href="https://colab.research.google.com/github/hanifhidayatt/data-science-toolkit/blob/main/Tutorial_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

array_2x2 = np.array([[1, 2],
                      [3, 4]])
print("1. Array of size 2x2:\n", array_2x2)

array_random_3x4 = np.random.rand(3, 4)
print("\n2. Random array of size 3x4:\n", array_random_3x4)

array_ones = np.ones((2, 3))
array_zeros = np.zeros((2, 3))
print("\n3a. Array of ones (2x3):\n", array_ones)
print("\n3b. Array of zeroes (2x3):\n", array_zeros)

array_6x3 = np.random.randint(0, 10, size=(6, 3))
array_3x6_transposed = array_6x3.T
print("\n4a. Original random array (6x3):\n", array_6x3)
print("\n4b. Transposed array (3x6):\n", array_3x6_transposed)

n, p, m = 4, 3, 2

A = np.random.rand(n, p)
B = np.random.rand(p, m)
dot_product = np.dot(A, B)

print("\n5a. Array A (4x3):\n", A)
print("\n5b. Array B (3x2):\n", B)
print("\n5c. Dot product (A dot B) result (4x2):\n", dot_product)

1. Array of size 2x2:
 [[1 2]
 [3 4]]

2. Random array of size 3x4:
 [[0.15156505 0.5684299  0.20797638 0.72092602]
 [0.38284691 0.25795421 0.43616419 0.89181296]
 [0.60014582 0.65630055 0.09879103 0.17154748]]

3a. Array of ones (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]

3b. Array of zeroes (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]

4a. Original random array (6x3):
 [[3 4 8]
 [5 7 1]
 [5 4 9]
 [0 5 7]
 [9 2 8]
 [1 9 1]]

4b. Transposed array (3x6):
 [[3 5 5 0 9 1]
 [4 7 4 5 2 9]
 [8 1 9 7 8 1]]

5a. Array A (4x3):
 [[0.87134659 0.26851682 0.51042131]
 [0.56069646 0.95192142 0.77454211]
 [0.93564589 0.11466526 0.5816942 ]
 [0.88568867 0.15894285 0.71376776]]

5b. Array B (3x2):
 [[0.74410153 0.89880495]
 [0.22201082 0.41885142]
 [0.83646751 0.97965344]]

5c. Dot product (A dot B) result (4x2):
 [[1.13493481 1.39567527]
 [1.27643126 1.66145323]
 [1.20824076 1.45884959]
 [1.29137286 1.56187984]]
